CREATE TABLE IF NOT EXISTS urls(
    id CHARACTER VARYING(6) PRIMARY KEY NOT NULL,
    original CHARACTER VARYING(2048) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT current_timestamp,
    expired_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);